name: Automerge For Humans

on:
  push:
    branches:
      - test

jobs:
  automerge-for-humans:
    if: 
      github.event.pull_request.draft == false &&
      (github.event.pull_request.user.login != 'asyncapi-bot' &&
       github.event.pull_request.user.login != 'dependabot[bot]' &&
       github.event.pull_request.user.login != 'dependabot-preview[bot]')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use a supported Node.js version

      - name: Install dependencies
        run: npm install 
        working-directory: ./.github/workflows/scripts/mailchimp

      - name: Get List of authors
        id: authors
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const { Octokit } = require('@octokit/rest');
            const { paginateRest } = require('@octokit/plugin-paginate-rest');

            const token = process.env.GITHUB_TOKEN;
            const prNumber = process.env.PR_NUMBER;
            const repository = process.env.GITHUB_REPOSITORY;

            async function getCoAuthors() {
              try {
                const octokit = new Octokit({ auth: token });
                const commitsResponse = await octokit.paginate("GET /repos/{owner}/{repo}/pulls/{pull_number}/commits", {
                  owner: "asyncapi",
                  repo: repository,
                  pull_number: prNumber,
                  per_page: 100,
                });

                const authors = commitsResponse
                  .map(data => ({
                    name: data.commit.author.name,
                    email: data.commit.author.email,
                    login: data.commit.author.login,
                  }))
                  .filter(author => author.login !== 'PR_sender_login')
                  .reduce((uniqueAuthors, author) => {
                    if (!uniqueAuthors.some(a => a.email === author.email)) {
                      uniqueAuthors.push(author);
                    }
                    return uniqueAuthors;
                  }, [])
                  .map(author => `Co-authored-by: ${author.name} <${author.email}>`)
                  .join('\n');
                console.log(authors);
                return authors;
              } catch (error) {
                console.error('Error fetching commits:', error);
                return null;
              }
            }

            // Execute the function and set the output
            const authorsOutput = await getCoAuthors();
            return { value: authorsOutput };

      - name: Automerge PR
        uses: pascalgn/automerge-action@22948e0bc22f0aa673800da838595a3e7347e584 #v0.15.6 https://github.com/pascalgn/automerge-action/releases/tag/v0.15.6
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          PR_NUMBER: ${{ github.event.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          MERGE_LABELS: "!do-not-merge,ready-to-merge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "${{ github.event.pull_request.title }} (#${{ github.event.number }})\n\n\n${{ steps.authors.outputs.value }}"
          MERGE_RETRIES: "20"
          MERGE_RETRY_SLEEP: "30000"
